### ISSUE TITLE
consider a `roll` implementation

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v4-core#174]
rather than forcing LPs to burn and re-mint positions, we could add an additional or replacement function, `roll`, that allows lps to migrate their position either intra- or inter-pools and does net accounting, only requiring the additional balance from the user and only crediting them with a remainder. this is relevant because it could make more sense to charge fees on this remainder if we're considering a fee on withdrawal regime

cc @moodysalem @snreynolds 

related to #130

**Comment by hensha256** [comment]
We've decided not to do this. Without protocol withdrawal fees (which are soon to be removed) it gives very little advantages besides some minor gas savings, and adds an additional complex function to the code.
