### ISSUE TITLE
consider a fee regime that credits hooks

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v4-core#175]
we could consider a fee collection regime that allows hooks to opt in to fees levied at any of the following points:

- fees on swap inputs
- fees on lp principal (or ideally, on net withdrawals from roll? see #174 )
- fees on lp fees

we could reserve up to 3 additional bits of hooks addresses to indicate that they may charge fees in any of these locations. if the bits are flipped, at the appropriate time hooks would call a function on the hook to fetch the current fee % and levy it, crediting it to the hook, before continuing with the user action

an alternative design here would be to credit a 3rd party (not the hooks contract) with these fees

a 3rd alternative would be for hooks to implement this logic by requiring an up-front payment of the fee before the corresponding swap/burn/roll/collect/whatever happens. this is, imo, not ideal as it requires special-casing in periphery + breaks the composability of these actions

**Comment by hensha256** [comment]
Done in #183
