### ISSUE TITLE
Consider making a custom type for PoolId

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#184]
Instead of using `bytes32 poolId` we could use `PoolId id` by creating a custom type

**Comment by abhithory** [comment]
hi @snreynolds , there is a library of the name "PoolId". so should we create its struct with the same "PoolId" name? or we can change it little bit? 

also in this struct will there be the only bytes32 data value or is there anything else that we should add?


i am really interested in working on this.
