### ISSUE TITLE
Increase fee bits and pack

### ISSUE THREAD

**Issue by hensha256** [Uniswap/v4-core#190]
Must come after #183 

The `Slot0` struct stores a number of fee-related variables in `uint8`. Namely: `protocolSwapFee`, `protocolWithdrawFee`, `hookSwapFee`, and `hookWithdrawFee`. Each of these uint8s stores 2 separate fee denominators: 4 bits for 0 to 1, and 4 bits for 1 to 0. Using only 4 bits for the denominator does not give us much granularity, and the smallest possible fee is 6.67% (1/15).

If all of these `uint8`s was increased to be a `uint16`, Slot0 would need more storage slots and increase gas drastically. However these is enough space for each fee to be given 6 bits instead of 4.

Proposal: Replace the 4 fee variables, with 2:
- `uint24 withdrawFees`
- `uint24 swapFees`

Where each uint24 is broken down as:
- 6 bits for protocol fee 0->1
- 6 bits for protocol fee 1->0
- 6 bits for hook fee 0->1
- 6 bits for hook fee 1->0

**Comment by HrikB** [comment]
I'll take on this one
