### ISSUE TITLE
[Bug]: Local snapshots do not match CI snapshots for fuzz tests

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#216]
### Describe the bug

There is an ongoing issue where `forge snapshot` locally does not match the CI snapshots. It is failing on on fuzz tests. I've checked the following which I thought could be related to this issue but are not:
- Local and CI using same fuzz runs. 
- No fuzz seed is being set in either env, which defaults to none. But, forge snapshot should already be using a deterministic seed, so this shouldn't be a problem.

### Expected Behavior

After updating the snapshot file locally, and pushing to your branch `forge snapshot --check` should pass in the linter.

### Additional context

PR reverted [here](https://github.com/Uniswap/v4-core/pull/215).

**Comment by zhongeric** [comment]
Fixed by #401
