### ISSUE TITLE
EIP-173 for Owned.sol

### ISSUE THREAD

**Issue by z0r0z** [Uniswap/v4-core#230]
### Describe the suggested feature and problem it solves.

Contract ownership discoverability benefit. Reasons no?

**Comment by zerosnacks** [comment]
It would also be recommended to use the 2-step ownership model to prevent any mistakes during transfer: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable2Step.sol or if you want to cut down on gas https://github.com/Vectorized/solady/blob/main/src/auth/Ownable.sol
