### ISSUE TITLE
Some code questions

### ISSUE THREAD

**Issue by cpppppp7** [Uniswap/v4-core#235]
### Describe the suggested feature and problem it solves.

/// @notice V4 decides whether to invoke specific hooks by inspecting the leading bits of the address that
/// the hooks contract is deployed to.
/// For example, a hooks contract deployed to address: 0x9000000000000000000000000000000000000000
/// has leading bits '1001' which would cause the 'before initialize' and 'after swap' hooks to be used.
👆👆
I cannot understand why this design is necessary... It seems sufficient for the hooks implementation contracts to declare them using `Hooks.Calls`.

**Comment by hensha256** [comment]
Hi @cpppppp7! Having these things in the hook's storage would mean having to SLOAD all of the flags in each transaction. Instead, it just has to reference `address(this)` which is much cheaper than an SLOAD

**Comment by cpppppp7** [comment]
Awesome! Great design @hensha256 👍!!! Respect!!

Another question is that in the example of LimitOrder, any normal trader's transaction will trigger the execution of the hooks contract, which means that those traders will pay more gas fees for their transaction to execute other people's limit orders. 

Wouldn't it make more sense that the trader who placed the limit order to cover the fees associated with the execution of the hooks contract?

**Comment by cpppppp7** [comment]
In v3, just-in-time LP transactions could be created by the Flashbot bundle. These transactions are independent, and traders only pay for their own transactions. If I implement JIT LP transactions using hooks, normal traders will incur additional gas fees caused by these JIT LP hooks. 

So, my question is, is there any solution for the hooks to return some gas fees to the trader?

**Comment by snreynolds** [comment]
Yes you are correct that any gas overhead that runs in the hook will be paid by the swapper or lp-er. Some hook logic may only run once per block (like twamm) in which case the arbitrageur or top of the block executor would front most of the gas heavy operations. 

Hooks do have the abilities to take fees but it would either come out of the swapper or lp-er.

Closing this for now but feel free to open more issues with anything that is concerning.
