### ISSUE TITLE
Consider moving external fee logic and functions to lib or separate contract

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#236]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

The fees logic has added quite a few new functions in the main `PoolManager.sol` entrypoint. It could be moved to another contract that manages all things related to hook and protocol fees, cleaning up the base contract.

In addition, could explore if any of the helper functions could be moved to Fees.sol lib.

**Comment by hensha256** [comment]
look at moving `setProtocolFee` into `ProtocolFees.sol`

**Comment by snreynolds** [comment]
This is #546

**Comment by snreynolds** [comment]
closed by https://github.com/Uniswap/v4-core/pull/546
