### ISSUE TITLE
refactor: use `Forge` over `npm` for `OpenZeppelin` 

### ISSUE THREAD

**Issue by 0xClandestine** [Uniswap/v4-core#237]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

Using Forge instead of NPM would significantly improve Foundry developer UX. Currently, if you want to install `v4-core` you'd use the command below:

```sh
forge i Uniswap/v4-core --no-commit
```

While this command successfully installs the repository like any other, there is an additional requirement. Developers must also navigate to the library and execute `npm install @openzeppelin/contracts`. Failing to do so will prevent Foundry from compiling properly.

To enhance the developer experience, it would be beneficial to replace NPM with Forge. By utilizing Forge instead, the installation process could be streamlined, eliminating the need for the additional step of manually installing OZ through NPM.

### Describe the desired implementation.

1) Install OZ via Foundry
2) Replace NPM imports with Forge imports

**Comment by MarcusWentz** [comment]
Requesting this change as well.

**Comment by snreynolds** [comment]
@245 closed this!
