### ISSUE TITLE
Improving LP earnings

### ISSUE THREAD

**Issue by AiSanta** [Uniswap/v4-core#238]
### Component

Hooks

### Describe the suggested feature and problem it solves.

When creating a Ranged Order, allow the user to add any of the 2 tokens of the pair as liquidity, regardless if the spot price is above or below the range of the order. For example in the ETH/USDC Pool:
* Allow to add liquidity with only ETH, when the Ranged Order is below the ETH spot price. (In v3 you can only add USDC in this case).
* Allow to add liquidity with only USDC, when the Ranged Order is above the ETH spot price. (In v3 you can only add ETH in this case).

Why this change? This will allow LPs to increase their earnings while minimizing loss of capital! Lets say you create a Ranged Order above the ETH spot price and add only USDC. If the price of ETH increases ABOVE the range, the algorithm would automatically switch the LP's position from USDC to ETH. This would allow the liquidity provider to earn aditional earnings from the increased value of ETH!

In the contrary case, when you create a Ranged Order below the ETH spot price and add only ETH, if the price of ETH decreases BELOW the range, the algorithm would automatically switch the LPs position from ETH to USDC, reducing the potential losses from holding a declining asset!

Of course this could only be done in Concentrated Liquidity pools!

### Describe the desired implementation.

With the new Hooks, I hope the geniuses at Uniswap can make this a reality and implement it as a Hook that can be applied to specific pools, like the ETH/USDC pool, without the need to change the entire protocol.

I am not a programer, so I leave this to you. Really hope you can make it!

### Describe alternatives.

Right now in v3, LPs are constantly afraid of losing money because of volatility, and unless you have a fancy bot that swaps liquidity automatically 24/7, their fear is completely understandable!

This change will allow to reduce the risk of losing money to a minimum! And in return, it will make LPs to feel safe to add more liquidity to the protocol! This will drive Uniswap's adoption to a whole new level!

**Comment by EphemerisNetwork** [comment]
The idea of automatically switching LP's token holdings based on price movements, if well-implemented, could indeed help LPs manage risk and potentially increase earnings but there are few concerns that come to mind,this complexity could result in higher gas costs which might be undesirable.Furthermore, there would be market impacts to think about.Adding this feature could potentially alter trading dynamics within the liquidity pools which might be potentially not appealing for traders.

**Comment by AiSanta** [comment]
Thank you for your response! First, higher gas prices are ok and even welcomed if you help create this hook! And second, of course it will impact trading and markets, it will make them more fair to every single trader! 98% of traders lose money because trading is very hard! Its imposible to predict the future! But with this hook, anyone can be a profesional trader! By just adding liquidity and becoming an LP, regular users and even traders can efficiently trade and hold for a period of time without the fear of losing money! This could be game changing not only for regular users, LPs, traders, and even Uniswap itself!

**Comment by aadams** [comment]
hey there, this is an interesting proposal, but would require a major re-write of core and is out of scope of the current project. thank you!
