### ISSUE TITLE
[Bug]: Found `BUSL-1.1` in place of an `MIT` LICENSE

### ISSUE THREAD

**Issue by misirov** [Uniswap/v4-core#260]
### Describe the bug

Uniswap has open sourced this repository and invited the community to collaborate. It seems that a BUSL-1.1 LICENSE has been added by mistake.

### Expected Behavior

To fix this bug, change all instances of
```diff
- BUSL-1.1`
+ MIT
```

**Comment by LefterisJP** [comment]
Why close this bug report @NoahZinsmeister. The OP is correct. According to your own comms you guys "opensourced" v4, no?

https://twitter.com/Uniswap/status/1668728551300907008
![2023-06-16_20-37](https://github.com/Uniswap/v4-core/assets/1658405/aeeb80b7-e366-4454-888a-cf205944c1cf)

**Comment by TimTinkers** [comment]
The actual license that needs to be used is `AGPL-3.0-only`, see [this issue arising from the use of Solmate](https://github.com/Uniswap/v4-core/pull/259#pullrequestreview-1483454450).

**Comment by bauti-defi** [comment]
anyone found a fix yet?

**Comment by bkellerman** [comment]
Ship it!

**Comment by gitr0n1n** [comment]
Was seeing if this has been solved yet. Bug still appears to be present.
