### ISSUE TITLE
Refactor `Calls` Custom Type

### ISSUE THREAD

**Issue by jtriley-eth** [Uniswap/v4-core#262]
### Component

Hooks, Gas Optimization, General design optimization (improving efficiency, cleanliness, or developer experience)

## Problem

The current definition of `Calls` is a struct, existing primarily in memory. Due to Solidity's memory layout rules related to structs, despite `Calls` being composed of booleans, the struct occupies eight slots, or 256 bytes of memory. Since the struct is largely used to check against an address bitmap, this is also a suboptimal choice for validation.

## Proposal

Consider changing the `Calls` struct to a type alias for a `uint160` bitmap for easy casting, cheaper validation, removing the need for memory when using `Calls`. The ergonomics of using curly brace + named argument syntax is preserved with the `newCalls` function.

```solidity
// old creation
Hooks.Calls memory calls = Hooks.Calls({
    beforeInitialize: true,
    afterInitialize: true,
    beforeModifyPosition: true,
    afterModifyPosition: true,
    beforeSwap: true,
    afterSwap: true,
    beforeDonate: true,
    afterDonate: true
});

// new creation
Calls calls = newCalls({
    beforeInitialize: true,
    afterInitialize: true,
    beforeModifyPosition: true,
    afterModifyPosition: true,
    beforeSwap: true,
    afterSwap: true,
    beforeDonate: true,
    afterDonate: true
});
```

## """Research"""

Findings on gas optimization and reference implementation can be found under "desired implementation".

### Describe the desired implementation.

https://github.com/jtriley-eth/bitmap-v-memory or comparable.

### Describe alternatives.

There is no second best.

**Comment by jtriley-eth** [comment]
Happy to take this on if it seems suitable for the codebase :)

**Comment by snreynolds** [comment]
Cool, yeah if you want to take it and set up a PR I'm happy to review. 

Usually we don't work on small optimizations like this (yet) since there is a lot of development left and usually we prefer readability over smaller optimizations. This is why you might see us close issues that also improve gas by only by a little, but I think in this case readability is not impacted and so I am leaning towards this being an overall good change!
