### ISSUE TITLE
Allow arbitrary callback data on Pool+Hook initialization

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-core#290]
### Component

Hooks, General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

When pools are initialized, allow for hook state initialization too

example function signature:

```solidity
    /// @notice Initialize the state for a given pool ID
    /// @param data arbitrary data to be passed to the hook
    function initialize(PoolKey memory key, uint160 sqrtPriceX96, bytes calldata data) external returns (int24 tick);
```

This will ensure that hooked pools get initialized consistently. Otherwise hook contracts will need to implement their own initialization functions.

**Example use-case**: the GeomeanOracle currently requires full-range liquidity. For stablecoin pairs, it would be nice to set the hook state such that only liquidity on (0.0, 2.0] is acceptable. This should offer better capital efficiency since the tokens don't need to provide liquidity for unreasonable prices

### Describe the desired implementation.

```solidity
    /// @inheritdoc IPoolManager
    function initialize(PoolKey memory key, uint160 sqrtPriceX96, bytes calldata data) external override returns (int24 tick) {
        // ... trimmed ...

        if (key.hooks.shouldCallBeforeInitialize()) {
            if (key.hooks.beforeInitialize(msg.sender, key, sqrtPriceX96, data) != IHooks.beforeInitialize.selector) {
                revert Hooks.InvalidHookResponse();
            }
        }

        // ... trimmed ...
    }
```

Providing the arbitrary data to `hook.beforeInitialize()` and `hook.afterInitialize()` is open for discussion

### Describe alternatives.

Alternative: hook initialization occurs independently in its implementation

```solidity
poolKey = IPoolManager.PoolKey(Currency.wrap(address(token0)), Currency.wrap(address(token1)), 3000, 60, IHooks(hook));
manager.initialize(poolKey, SQRT_RATIO_1_1);

// initialize the hook state as a separate step
// hook developers have free reign on function signature etc
bytes memory data = abi.encode(....);
hook.initializeHook(poolKey, data);
```

### Additional context.

Happy to pick this up, if its desirable

**Comment by ewilz** [comment]
closing in favor of https://github.com/Uniswap/v4-core/issues/307 which is broader in scope, but would include this change. Feel free to reopen if this doesn't address this issue.
