### ISSUE TITLE
Investigate ERC1155 Gas Costs

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#294]
This will help inform pros/cons for the 1155 use case.
If promising, rewrite custom gas efficient ERC1155 contract instead of OZ's.

**Comment by EphemerisNetwork** [comment]
Investigating variations of the 1155 contracts such as https://github.com/DonkeVerse/ERC1155D might be worthy for optimizing gas efficiency.

**Comment by zhongeric** [comment]
Closed by #379
