### ISSUE TITLE
Consider allowing EOAs to call `lock` directly

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v4-core#298]
### Component

Lock and Call

### Describe the suggested feature and problem it solves.

we could allow EOAs to call `lock` directly on the core, with callers specifying a router address on which `lockAcquired` would be called

the upside of this approach is that the `msg.sender` could be trustlessly threaded through to hooks, for use cases such as https://github.com/jdubpark/Uniswap-Hooks/blob/main/contracts/OldAccountHook.sol

the downside (?) is that anyone could trigger the canonical PoolManager to call `lockAcquired(...)` on any address, with at least partial control over the calldata.

h/t @marktoda for the idea

**Comment by naddison36** [comment]
I support this proposal.

The `sender` in all the hook calls is not going to be of any value if it is mostly the Universal Router or a DEX aggregator

**Comment by hensha256** [comment]
I'm struggling to see how you could write a secure router for this code. Maybe I'm missing something...

Before this change, a router can add `msg.sender` into the data it passes into the lock. Then in the callback, it has access to the `msg.sender`. This would allow it to securely take tokens from the correct user (using `Permit2` or regular `transferFrom`) to call `settle` and pay contract debts.

After this change - any value of `sender` can be passed into the router so it cannot trust it. How can a router ever know who to pull tokens from? And whether they actually wanted to execute this transaction?

**Comment by marktoda** [comment]
It should require msg.sender == poolmanager in lockAcquired  and we should have poolmanager pass in sender as msg.sender

**Comment by hensha256** [comment]
i seeee so you’re suggesting we add another parameter to the lock callback?

**Comment by marktoda** [comment]
yea think thats imperative here, also another parameter for hook callbacks with the msg.sender to get the actual benefit of this

**Comment by damianrusinek** [comment]
Assuming this idea gets implemented, hooks and pool operators (that get the lockAcquired callback) could get the address of the initial locker (`getLock(0)`) instead of passing the sender's address.

**Comment by damianrusinek** [comment]
After some discussions and rethinking the proposal, I would say that this proposal is similar to the flash loan flow, where the router is like flash loan receiver.

It has to make sure that the `lockAcquired` call comes from the PoolManager (`msg.sender == poolmanager`) anyway (both, in the current architecture and in the proposed one). Just like the flash loan receivers do to protect themselves from a callback call from untrusted address.

Additionally, if the router was meant to be called only by privileged initiators, it has to take care of that, just like some flash loan receivers.

Last, but not least, the router can get the last locker from the PoolManager. It can the query the `LOCKERS_SLOT + length()` (https://github.com/Uniswap/v4-core/blob/main/src/libraries/Lockers.sol#L9). There is `getCurrentLocker` in library, but it is not exposed in PoolManager.

**Comment by ferencdg** [comment]
If the flow is EOA -> GoodRouter -> PoolManager -> Hook, cannot just the router forward EOA to the Hook, and the Hook would store all user data under the (GoodRouter, EOA) tuple? This way, if there is a BadRouter who would like to spoof EOA, then the Hook would identify it as (BadRouter, EOA)
