### ISSUE TITLE
Pass swap parameters to IDynamicFeeManager.getFee()

### ISSUE THREAD

**Issue by atiselsts** [Uniswap/v4-core#302]
### Component

Hooks

### Describe the suggested feature and problem it solves.

`getFee()` function of the `IDynamicFeeManager`  interface takes pool key as the only parameter. The hook deployer might want to change the swap fee depending on the swap parameters itself, not just the state of the pool. For example:
* provide a discount to "loyal customers" (with more than `n` swaps in the pool) or large swappers;
* make the fee depend on the direction of the swap, for example reduce the fee if the swap makes the pool more balanced; increase the fee in the opposite direction, to penalize arbitragers;
* etc.

### Describe the desired implementation.

Replace:

    function getFee(IPoolManager.PoolKey calldata key) external returns (uint24);

with

    function getFee(IPoolManager.PoolKey calldata key, IPoolManager.SwapParams calldata params) external returns (uint24);

And replace:

    totalSwapFee = IDynamicFeeManager(address(key.hooks)).getFee(key);

with:

    totalSwapFee = IDynamicFeeManager(address(key.hooks)).getFee(key, params);

### Describe alternatives.

It's already possible to implement these behaviors, because `beforeSwap()` does take swap params as an argument. The params can be remembered and subsequently used in `getFee()`. Still, passing them directly to `getFee()` simplifies the design of the dynamic fee hook.

**Comment by Swapnapratim** [comment]
Hey @atiselsts, I am working on this feature but I am wondering what should be the impact on gas fees and performance due to this change?

**Comment by Swapnapratim** [comment]
Hello @atiselsts  I have submitted a PR would you like to have a check!

**Comment by atiselsts** [comment]
Hi @Swapnapratim 
1. I'm just a community member, not able to tell if you're doing all that's expected in your PR.
2. This issue is potentially superseded by #307, best check with @ewilz who is with Uniswap.

**Comment by ewilz** [comment]
ahh sorry, missed this issue. Yes, @azflin is working on this atm.

**Comment by atiselsts** [comment]
done in PR #332

**Comment by atiselsts** [comment]
done in PR #332
