### ISSUE TITLE
Arbitrary bytes for hooks callbacks

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-core#307]
### Component

Hooks

### Describe the suggested feature and problem it solves.

All PoolManager functions that have before and after hooks should accept `bytes calldata data` that is handed to all hook callbacks. These could be good to use for things involving proofs or zkproofs.

IDynamicFeeManager(hook).getFee(key) should also probably accept dynamic bytes as well as the same information as before/after Swap.

**Comment by Swapnapratim** [comment]
Hey @ewilz  I have submitted a PR on the feature #302 would you like to have a check!
But I am wondering by passing extra swap params how shall it affect overall gas pricing and efficiency?
