### ISSUE TITLE
Migrate All tests to Foundry

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-core#315]
### Describe the suggested feature and problem it solves.

Needing access to node-js is causing some dev-x issues, and instead of patching those, it seems like somewhat low effort to just get all our tests migrated and delete hardhat.

merged migrations:

- [x] sqrtPriceMath https://github.com/Uniswap/v4-core/pull/317
- [x] tickMath https://github.com/Uniswap/v4-core/pull/306
- [x] FullMath (https://github.com/Uniswap/v4-core/pull/314))
- [x] TickBitmap https://github.com/Uniswap/v4-core/pull/320
- [ ] SwapMath https://github.com/Uniswap/v4-core/pull/323
- [ ] PoolManager

**Comment by ewilz** [comment]
If anyone feels like contributing to this, please leave a comment with which file you're migrating. This would be SO HELPFUL!

**Comment by MwitahJob** [comment]
Working on swapMath.spec.ts

**Comment by MwitahJob** [comment]
Working on swapMath.spec.ts

**Comment by MwitahJob** [comment]
Hello could you help me a little, they are some functions imported into the hardhat test which are written in typescript.

``` solidity
import { encodeSqrtPriceX96, expandTo18Decimals } from './shared/utilities'
```

If you don't mind, how do I go around it? Sorry it's my first time.🙂

**Comment by gitcoindev** [comment]
Hi! I would like to contribute and pick up SqrtPriceMath, will open a PR till Tuesday EOD.

**Comment by gitcoindev** [comment]
Hi @ewilz I second the question from @MwitahJob . just after I created a skeleton I encountered the same functions. If I understand correctly, the typescript helper function implementations used in tests must be ported to solidity.

In this particular case for expandTo18Decimals we have number * 10^18

```
export function expandTo18Decimals(n: number): BigNumber {
  return BigNumber.from(n).mul(BigNumber.from(10).pow(18))
}
```

and we could potentially use an example from Solidity types https://docs.soliditylang.org/en/v0.8.20/types.html for `UFixed256x18` 

```
 /// Turns a uint256 into a UFixed256x18 of the same value.
    /// Reverts if the integer is too large.
    function toUFixed256x18(uint256 a) internal pure returns (UFixed256x18) {
        return UFixed256x18.wrap(a * multiplier);
    }
```

I just want to double check if this is the correct way or perhaps Uniswap already has a preferred Solidity library to use?

**Comment by gitcoindev** [comment]
`encodeSqrtPriceX96` looksy tricky as well, I need to (slowly) digest https://blog.uniswap.org/uniswap-v3-math-primer

**Comment by MwitahJob** [comment]
> `encodeSqrtPriceX96` looks tricky as well, I need to (slowly) digest https://blog.uniswap.org/uniswap-v3-math-primer

Hey am new to open source contributing, could we work on this together?

**Comment by gitcoindev** [comment]
@MwitahJob sure, I found a price helper library in Arbitrum code for Uniswap, which might help (line 57) https://vscode.blockscan.com/arbitrum-one/0x6b89952eab134f5ab10aafb9327a29853715cd96 you can potentially start here, try to see of this works for you.

**Comment by MwitahJob** [comment]
@gitcoindev ok sure,  thanks, lemme check it out.

**Comment by MwitahJob** [comment]
> @MwitahJob sure, I found a price helper library in Arbitrum code for Uniswap, which might help (line 57) https://vscode.blockscan.com/arbitrum-one/0x6b89952eab134f5ab10aafb9327a29853715cd96 you can potentially start here, try to see of this works for you.

The two functions are quite different: ``` encodeSqrtPriceX96 ``` from v4-core accepts two ```BigNumberish``` numbers while on Arbitrum code it accepts a boolean and a number also implementations are quite different also.

**Comment by ewilz** [comment]
to expand to 18 decimals in solidity you can just write `2 ether`

**Comment by MwitahJob** [comment]
> HI sorry, just seeing these comments. re: `encodeSqrtPrice` If you need a very specific number we can always hardcode them in solidity like this example: https://github.com/Uniswap/v4-core/pull/306/files#diff-317ef0b3084261c2cae1221b7990633505ace7f6822b404c89039f77f471a6cdR74
> 
> corresponds to line 42 in the [test/TickMath.spec.ts](https://github.com/Uniswap/v4-core/pull/306/files#diff-b8f7dbb96f5f266f9015b76203c4db40ce257569d8b821227ef24d3f167be54b) it's eliminating

So I can just manually calculate below to compare with ```sqrtQ``` ?
``` solidity
 const priceTarget = encodeSqrtPriceX96(101, 100);
```

**Comment by ewilz** [comment]
> o I can just manually calculate below to compare with `sqrtQ` ?

umm yah?? some common ones are already hard-coded, possible we might want to hardcode more as tests get migrated... https://github.com/Uniswap/v4-core/blob/main/test/foundry-tests/utils/Deployers.sol#L18

**Comment by MwitahJob** [comment]
> > o I can just manually calculate below to compare with `sqrtQ` ?
> 
> umm yah?? some common test ones are already hard-coded, possible we might want to hardcode more as tests get migrated... https://github.com/Uniswap/v4-core/blob/main/test/foundry-tests/utils/Deployers.sol#L18

okay sure

**Comment by gitcoindev** [comment]
Hi @ewilz I opened a PR, would be grateful if you had a look whenever you find time.

**Comment by gitcoindev** [comment]
I will try to migrate TickBitmap.spec.ts next.

**Comment by nagrarohit** [comment]
hey! @MwitahJob are you still working on swapmath test . I would like to work alongside you on this test if you dont mind.

**Comment by MwitahJob** [comment]
> hey! @MwitahJob are you still working on swapmath test . I would like to work alongside you on this test if you dont mind.

Yeah sure

**Comment by nagrarohit** [comment]
> > hey! @MwitahJob are you still working on swapmath test . I would like to work alongside you on this test if you dont mind.
> 
> 
> 
> Yeah sure 

can you share your progress.
i mean a link or something.

**Comment by MwitahJob** [comment]
> > > hey! @MwitahJob are you still working on swapmath test . I would like to work alongside you on this test if you dont mind.
> > 
> > 
> > Yeah sure
> 
> can you share your progress. i mean a link or something.

I have been a little busy lately, could I update you tomorrow if you don't mind?

**Comment by nagrarohit** [comment]
> > > > hey! @MwitahJob are you still working on swapmath test . I would like to work alongside you on this test if you dont mind.
> 
> > > 
> 
> > > 
> 
> > > Yeah sure
> 
> > 
> 
> > can you share your progress. i mean a link or something.
> 
> 
> 
> I have been a little busy lately, could I update you tomorrow if you don't mind?

For sure dear.

**Comment by gitcoindev** [comment]
All right, together with @ewilz we are four people. I will try to tackle Tick.spec.ts and leave the rest to you guys.

**Comment by MwitahJob** [comment]
> All right, together with @ewilz we are four people. I will try to tackle Tick.spec.ts and leave the rest to you guys.

Nice work buddy.

**Comment by nagrarohit** [comment]
> > All right, together with @ewilz we are four people. I will try to tackle Tick.spec.ts and leave the rest to you guys.
> 
> Nice work buddy.

@MwitahJob do you have any updates dear.

**Comment by MwitahJob** [comment]
> > > All right, together with @ewilz we are four people. I will try to tackle Tick.spec.ts and leave the rest to you guys.
> > 
> > Nice work buddy.
> 
> @MwitahJob do you have any updates dear.
> 

Yeah

**Comment by nagrarohit** [comment]
> > > > All right, together with @ewilz we are four people. I will try to tackle Tick.spec.ts and leave the rest to you guys.
> > > 
> > > 
> > > Nice work buddy.
> > 
> > 
> > @MwitahJob do you have any updates dear.
> 
> Yeah

can i have a look @MwitahJob

**Comment by MwitahJob** [comment]
@nagrarohit I will share the tests I have written in a few😊

**Comment by nagrarohit** [comment]
if i have a look i will try to help at my level best. @MwitahJob

**Comment by MwitahJob** [comment]
@nagrarohit sure, give me a few minutes

**Comment by nagrarohit** [comment]
Thanks for sharing @MwitahJob , i will update you by tomorrow.

**Comment by MwitahJob** [comment]
Hey @ewilz , could you give me a better method to implement this:
``` javascript
 it('swap one for zero exact in capped', async () => {
        await snapshotGasCost(
          swapMath.getGasCostOfComputeSwapStep(
            encodeSqrtPriceX96(1, 1),
            encodeSqrtPriceX96(101, 100),
            expandTo18Decimals(2),
            expandTo18Decimals(1),
            600
          )
        )
      })
```
Here is my version:
``` solidity
 function testSwapOneForZeroExactInCapped() public {
        uint256 gasCost =
            SwapMath.getGasCostOfComputeSwapStep(SQRT_RATIO_1_1, SQRT_RATIO_101_100, 2 ether, 1 ether, 600);

        assertGt(gasCost, 0);
    }

```

**Comment by MwitahJob** [comment]
Hello @nagrarohit

**Comment by nagrarohit** [comment]
> Hello @nagrarohit

@MwitahJob Hi Dear! How are You.

**Comment by MwitahJob** [comment]
> > Hello @nagrarohit
> 
> @MwitahJob Hi Dear! How are You.

Am cool, how did it go?

**Comment by nagrarohit** [comment]
> ol, how did it go?



> > > Hello @nagrarohit
> > 
> > 
> > @MwitahJob Hi Dear! How are You.
> 
> Am cool, how did it go?

It is looking good to me. And error free. Now let see if it gets merged.

**Comment by MwitahJob** [comment]
I can help you work on one

**Comment by nagrarohit** [comment]
> I can help you work on one

which one

**Comment by MwitahJob** [comment]
Choose any, we will just struggle with it🤣🤣

**Comment by nagrarohit** [comment]
ok . Actually i will look for it, and then inform you buddy.

**Comment by MwitahJob** [comment]
OKAY COOL

**Comment by nagrarohit** [comment]
@ewilz I think @MwitahJob have opened #323 and it is about the Swapmath. But you have not listed it in the tasks for swapmath. So can you please do it.

**Comment by MwitahJob** [comment]
Lemme check it out

**Comment by Uttam-Singhh** [comment]
Hello @ewilz 
Is Pool Manager's contract test migration still left? If yes - Can I work on that?

**Comment by smatthewenglish** [comment]
I took a crack at porting some of the remaining functionality from `PoolManager.spec.ts` to `PoolManager.t.sol` in [pr 354](https://github.com/Uniswap/v4-core/pull/354), if this is helpful and i'm on the right track lmk and i'll keep going! 🚀

**Comment by snreynolds** [comment]
SwapMath migration in progress here https://github.com/Uniswap/v4-core/pull/363

**Comment by sm-stack** [comment]
@ewilz Just made a pull request for migrating PoolManager test to foundry #367
