### ISSUE TITLE
What's the legal basis for the BUSL-1.1 license?

### ISSUE THREAD

**Issue by seraphx333** [Uniswap/v4-core#338]
### Describe the bug

**First of all, I AM NOT A LAWYER, so this is not legal advice.**

As far as I'm aware Uni V4 uses V3 core contracts, which are now officially GPL-2-0-or-later after the BUSL-1.1 expiration on April 1st 2023. Any software that directly integrates with it (even just as a library) has to be GPL too. So what's the legal basis to publish Uni V4 with a BUSL-1.1 license when it uses and integrates a plethora of underlying GPL-2.0 licensed libraries?

IANAL but it doesn't seem that this would hold up in court. Besides, it's quite something to proclaim that Uniswap V4 is "built by the community" but then you completely gate it behind corporate interests after you received said community's free labor?

Would appreciate if you could clear me up how it is legal or compliant to use BUSL-1.1 in this case.

Source of claims: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#IfLibraryIsGPL
![image](https://github.com/Uniswap/v4-core/assets/113269670/207af9a3-d808-4cb7-b8f1-a551fbfd8b9a)

### Expected Behavior

Comply with the license agreement of GPLv2

**Comment by sawproduction** [comment]
Same qs

**Comment by danrobinson** [comment]
That's not how copyright works. Uniswap Labs owns the copyright to the Uniswap v3 codebase, so they're free to make derivative works of it and license those derivative works under whatever licenses they want. They don't have to use the GPL to license the v3 code _from themselves_.

**Comment by seraphx333** [comment]
> That's not how copyright works. Uniswap Labs owns the copyright to the Uniswap v3 codebase, so they're free to make derivative works of it and license those derivative works under whatever licenses they want. They don't have to use the GPL to license the v3 code _from themselves_.

Appreciate the clarification, thanks.

**Comment by arnolwijaya77** [comment]
Have no idea
