### ISSUE TITLE
Why use Transfer??

### ISSUE THREAD

**Issue by Aryan9592** [Uniswap/v4-core#339]
### Describe the bug

I have noticed that many contracts have used `transfer` method in order to make transactions, whereas `call` is usually preferred!!

### Expected Behavior

Let me explain how it could cause harm to contracts -

Here's a code snippet from `PoolManager.sol`:

```
/// @inheritdoc IPoolManager
function take(Currency currency, address to, uint256 amount) external override noDelegateCall onlyByLocker {
    _accountDelta(currency, amount.toInt128());
    reservesOf[currency] -= amount;
    currency.transfer(to, amount);
}
```
There's a problem with `transfer` that, if by chance a transaction took more than 2300 gas, the transaction will fail. But in `call` you can set your own gas and even set a limit if anyone wants.

**Now how someone could benefit from this vulnerability?** 
Actually, there won't be any problem with `transfer` in case you are interacting with this function using 'Externally Owned Account' cuz they take up less gas, but if an 'Attacker' used a contract account and didn't implemented any `receive` method intentionally, the transaction will is more likely to fail at that moment, plus as you can notice 2nd line of this particular function -> It even reduces the `reservesOf` of that particular `currency`. You can dive more deep in it like why and how?

And Do tell me if I am kind of wrong here, It be a good learning opportunity that how transfer doesn't showed up any vulnerability in this case

**Comment by atiselsts** [comment]
The problems you describe apply to native ETH `transfer`s, while the example code snippets uses a custom type `Currency`, which just happens to have a function with the same name. The implementation of this `transfer` function is part of the [v4 core code](https://github.com/Uniswap/v4-core/blob/main/contracts/types/Currency.sol#L35).

**Comment by Aryan9592** [comment]
I see, Thanks man!!
