### ISSUE TITLE
Certain hooks should have direct access to Pool assets

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-core#344]
### Component

Hooks/Pool

### Describe the suggested feature and problem it solves.

I am trying to develop a hook, that would invest some of the pool assets into yield farming protocols (the ones that live in ranges far away from the current price). Whenever the user wants to provide liquidity, he would directly deposit it through the pool. In case the current pool price is far away from the range in which the user wants to provide liquidity, I would just deposit the the pool assets into a yield farming protocol.

However, the Hooks doesn't seem to have access to the assets in the pool (I cannot ERC20 approve the Hooks from the Pool). 
Of course, I could always  provide liquidity to the pool **through** the hook, and not directly through the pool, but in this case it would be less transparent for the user. For example, he would not be able to query his ranges through the Pool contract.

### Describe the desired implementation.

Maybe call the init function of the Hook through delegate call from the Pool. This way the hook creators can give special permissions to the hook (like allowing ERC20 transfer of all the pool assets)

**Comment by atiselsts** [comment]
I'm not sure if making some token allowances in a way that's not clearly visible to the user is a good idea from the security point of view.

**Comment by ferencdg** [comment]
If a user interacts with the pool, then we can assume he trusts the pool/verified the code. The Hooks are assigned to the pool at pool creation time (let's say the hooks are not upgradeable smart contracts). In this case if the user trusts the pool, shouldn't he also verify/trust the hook?

**Comment by danrobinson** [comment]
Your suggested change would allow a hook to drain all assets held by all v4 pools.

In general the singleton does not track the balances of individual pools (which is a key part of the gas savings in v4), so there is no safe way for a hook to be allowed to spend tokens that belong to its pool without it being able to steal money from other pools.

You could try creating wrapped tokens for each of the assets and spending the tokens from the wrapper contract. But admittedly then swappers will have to wrap and unwrap tokens when they trade them.

**Comment by ferencdg** [comment]
> Your suggested change would allow a hook to drain all assets held by all v4 pools.
> 
> In general the singleton does not track the balances of individual pools (which is a key part of the gas savings in v4), so there is no safe way for a hook to be allowed to spend tokens that belong to its pool without it being able to steal money from other pools.
> 
> You could try creating wrapped tokens for each of the assets and spending the tokens from the wrapper contract. But admittedly then swappers will have to wrap and unwrap tokens when they trade them.

really smart idea, thank you
