### ISSUE TITLE
Explore consolidating hook.beforeSwap() and hook.getFee()

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-core#347]
### Describe the suggested feature and problem it solves.

These calls are extremely similar, except one returns a fee value and one returns a safety selector value. You'd probably only need to use one or the other depending on whether you need a dynamic fee. Otherwise, they both have all the same access/capabilities.

relevant code
```
        if (key.hooks.shouldCallBeforeSwap()) {
            if (key.hooks.beforeSwap(msg.sender, key, params, hookData) != IHooks.beforeSwap.selector) {
                revert Hooks.InvalidHookResponse();
            }
        }

        // Set the total swap fee, either through the hook or as the static fee set an initialization.
        uint24 totalSwapFee;
        if (key.fee.isDynamicFee()) {
            totalSwapFee = IDynamicFeeManager(address(key.hooks)).getFee(msg.sender, key, params, hookData);
            if (totalSwapFee >= 1000000) revert FeeTooLarge();
        } else {
            // clear the top 4 bits since they may be flagged for hook fees
            totalSwapFee = key.fee.getStaticFee();
        }
```

pros: 
- code consolidation
- eliminate the awkwardness in the capability to enable both

cons:
- breaks cleanliness of hooks interfaces (beforeSwap would have a different returnVal)

Gas savings and cleanliness are determining factors?

### Describe alternatives.

...leave as is :)

**Comment by snreynolds** [comment]
One other alternative is that we could cache the fee and not have to call out to getFee each time?

**Comment by paco0x** [comment]
> One other alternative is that we could cache the fee and not have to call out to getFee each time?

Can we use this mechanism to prevent the frontrunning issue somehow?

For now, the contract calls `hook.getFee()` to get the fee ratio before every swap.

If there's a malicious hook contract, setting the fee ratio to `0` to deceive the router or other off-chain quoting services. Once users send tx to swap through this pool, the hook admin can front-run the tx by setting the fee ratio to a high value and causing users' loss.

**Comment by hensha256** [comment]
Now that fees are push not pull #501 this is no longer needed
