### ISSUE TITLE
Replace ERC-1155 With ERC-6909 For Multi-Token Accounting

### ISSUE THREAD

**Issue by jtriley-eth** [Uniswap/v4-core#357]
### Component

Singleton, 1155 Balances, Pool Actions (swap, modifyPosition, donate, take, settle, mint), Gas Optimization, General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

The current interface for multi-token accounting is [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155), which contains constraints for unnecessary callbacks, unnecessary batching, and all-or-nothing transfer delegation. Replacing ERC-1155 with [ERC-6909](https://eips.ethereum.org/EIPS/eip-6909) reduces code size, improves the transfer delegation system, and improves gas efficiency for deployment, transfers, and burning.

### Describe the desired implementation.

Replace ERC-1155 with ERC-6909 in the inheritance tree, replace the callback-based burn mechanism with a single burn function, and remove the ERC1155Receiver interface.

### Describe alternatives.

The ERC-6909 interface does constrain a total supply variable, leading to an additional disk write on mint and burn.

**Comment by snreynolds** [comment]
Related to https://github.com/Uniswap/v4-core/issues/197

**Comment by snreynolds** [comment]
https://github.com/Uniswap/v4-core/issues/294

**Comment by zhongeric** [comment]
We're actively exploring how we can work towards a standard (either 6909 in particular or 6909-like), and so let's keep this issue open and reference it in any future PRs / work on this front

**Comment by hensha256** [comment]
Closing as its done
