### ISSUE TITLE
Allow One way(single direction) liquidity position only

### ISSUE THREAD

**Issue by RobinNagpal** [Uniswap/v4-core#385]
### Describe the suggested feature and problem it solves.
Right now LPs are mostly on the losing side(in exchange of fee earnings), that i.e. they are left with the tokens which have less value.

We can enhance liquidity provision, so they can provide two types of liquidity

1) Two way - i.e. the current way. May be 50% of the fees earned goes to these type of LPs
2) One way - LPs which are long or short on one type of token - 50% of the fees can go here. Out of this 50% fee, half of it goes in each direction. Like half for longs and half for shorts.

So if out of 100 positions for the second case, suppose 99% are long on a certain side, then 1% who short, can earn 1/2 of dynamic fee(second option).

This allows for adding liquidity for "No Impermanent Loss" scenarios, and also the scenarios where a person has boosted earnings in exchange for impermanent loss.

**For example**

- The current value of ETH is ETH/USDC pool is $1750.
- I am long on ETH and I provide USDC in ETH/USDC Pool in the range $1800-$2000. If anyone was to sell ETH in this range, it will be swapped by the USDC I proved, but my liquidity will be used and converted in one direction only
- If I am short on ETH, I can provide ETH in $1500-$1700

**Now what if everyone is long?**
- Equal fees can be distributed on both long and short.
- if one person provides liquidity on the short side, they earn the entire short side fees.

So this is another way to provide liquidity, and we keep the current way too.

### Describe the desired implementation.
Add a flag to Position.Info to track if the position is one sided or not

During the swap we use the two way LP positions and also the ones that match the direction.

**Comment by aadams** [comment]
hey there, while this is an interesting proposal, it would require a major re-write of core and is out of the scope of this.
