### ISSUE TITLE
Support pools for non-ERC-20 multi-token contracts

### ISSUE THREAD

**Issue by h4l** [Uniswap/v4-core#394]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

I propose allowing Pools to hold tokens from non-ERC20 contracts.

Currently, a pool's tokens must be either native ETH or ERC-20 contracts. Uniswap V4 itself uses a singleton contract design to avoid needing to deploy new contracts per-pool, but by requiring ERC-20 tokens, it prevents integrating protocols following the same pattern to improve their own efficiency.

Consider a protocol that exposes a dynamic number of fungible tokens based on user actions. For example, a lending protocol that holds assets and provides a tokenised receipt representing deposits. Or an NFT liquidity protocol that translates NFTs into fungible tokens by minting units of a fungible proxy token for NFTs deposited into it. 

To integrate with current AMMs and Uniswap V4, protocols like these need to instantiate ERC-20 contracts for each separate token they produce. In principle, they could use a single multi-token contract — such as ERC-1155 — to represent a variable number of token types, but these multi-token contracts are not supported by Uniswap AMMs, which discourages their use.

If Uniswap V4 supported multi-token contracts, such a protocol could create pools that directly-reference the integrating protocol's own singleton token contract, rather than creating ERC-20 instances for each token type.

### Describe the desired implementation.

One approach could be to allow the `Currency` type to reference ERC-1155 (or perhaps the yet-to-be-finalised EIP-6909). Full support would require an additional `int256` for the `tokenId`, but a future-compatible compromise could be to use the remaining 96 bits from the contract address in the 256-bit word as the `tokenId` (or 95 if 1 bit were used to explicitly mark non-ERC-20 addresses). 95/96 bits is plenty for an implementation that sequentially allocates IDs (and probably enough to randomly allocate IDs in a way that handles clashes).

Alternatively, I wonder if it would be possible to delegate responsibility for token transfers and or holding tokens to hook contracts, so that the PoolManager itself does not need to be aware of token standards. Perhaps a specialised/trusted vault hook could be produced per-token-standard to provide future-compatible support for emerging token standards.

**Comment by hensha256** [comment]
hey there, while this is an interesting proposal, it's out of scope for this version of the protocol. Thank you for your proposal!
