### ISSUE TITLE
Accessing the end user's address from within a hook

### ISSUE THREAD

**Issue by ra-phael** [Uniswap/v4-core#396]
### Component

Hooks

### Describe the suggested feature and problem it solves.

As I was developing a hook I realized that the first param passed to a hook, `sender`,  is not what I expected it to be. For a swap for example:

https://github.com/Uniswap/v4-core/blob/5fb47b1d659a4ca91b6077a94d56221e806d7c82/src/PoolManager.sol#L251

So most likely it won't be the address of the end user initiating a transaction (be it an EOA or smart account wallet) but that of a router calling the PoolManager... which is not as interesting if we want to perform some logic involving the user's address in a hook, like in this example: https://github.com/jdubpark/Uniswap-Hooks/blob/main/contracts/OldAccountHook.sol

What are your thoughts around the best approach to get the end user's address from within a hook then? Using `tx.origin`? Or is it expected that routers will take on that responsibility - which might be very significant - of properly forwarding the address as part of `hookData`?

**Comment by hensha256** [comment]
Thanks for your suggestion! This is actually already being solved through issue #298, which should be implemented by the team shortly.

Going to close your issue so we dont have duplicates open.
