### ISSUE TITLE
Update tests to reference `IPoolManager`

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-core#416]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

Following up on https://github.com/Uniswap/v4-core/pull/412, the `IPoolManager` was found to be out of sync with the external signatures in `PoolManager`

This issue suggests updating the tests to interact with the PoolManager through its `IPoolManager`

### Describe the desired implementation.

Update tests that directly use `PoolManager` to use `IPoolManager` instead

### Describe alternatives.

N/A

**Comment by nishim3** [comment]
I have gone through the repo, and I cannot see any tests where the ```PoolManager``` is being called instead of the ```IPoolManager``` contract. I think this issue is resolved now.

**Comment by saucepoint** [comment]
looks like most tests were refactored to use the `Deployers` test helpers which is a good start. But it looks like `Deployers` is still using PoolManager and not the interface.

while I think this issue should be resolved before deployment, I think preemptively using the interface adds friction to core contributions (changes to function signatures need to be updated twice)
