### ISSUE TITLE
[Bug]: cannot query important pool data like ticks, tickBitmap outside from Pool/PoolManager

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-core#426]
### Describe the bug

in UniswapV3 ticks, tickBitmap were accessible from outside the Pool/PoolManager smart contract, but they are no longer visible:

declaration of pools in PoolManager:
mapping(PoolId id => Pool.State) public pools;

 struct State {
        Slot0 slot0;
        uint256 feeGrowthGlobal0X128;
        uint256 feeGrowthGlobal1X128;
        uint128 liquidity;
        mapping(int24 => TickInfo) ticks;
        mapping(int16 => uint256) tickBitmap;
        mapping(bytes32 => Position.Info) positions;
    }
    
I would like to write a hook that needs access to those variables, but cannot with the current v4-core code.

### Expected Behavior

make them available

**Comment by hensha256** [comment]
You should be able to use our `extsload` functions. They allow you to view _any_ storage slot in the whole PoolManager contract
