### ISSUE TITLE
Change Deployers.createPool from private to internal or public

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-core#427]
### Describe the suggested feature and problem it solves.

please make this function internal or public:

function createPool(
PoolManager manager,
IHooks hooks,
uint24 fee,
uint160 sqrtPriceX96,
bytes memory initData
) private returns (PoolKey memory key, PoolId id)

The general flow of creating hooks in Tests is:

create the PoolManager with Deployers.createPoolManager()
create the Hook and pass in the poolManager
create the pool with Deployers.createPool

**Comment by snreynolds** [comment]
Closing - that PR should help pool creation. Let us know if this doesn't resolve your request
