### ISSUE TITLE
Allow settling open deltas for other callers

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#436]
### Component

Lock and Call, Delta accounting

### Describe the suggested feature and problem it solves.

One interesting feature could be to allow any positive deltas to be resolved for any other caller. We could add this by adding an address parameter to the settle function. 

### Additional context.

Enhancement along with https://github.com/Uniswap/v4-core/issues/435

**Comment by hensha256** [comment]
Closing for now as we have decided to replace this idea with #463
