### ISSUE TITLE
[Bug]: IClaim.balanceOf function signature isn't define as view function

### ISSUE THREAD

**Issue by Gevarist** [Uniswap/v4-core#455]
### Describe the bug

Missing `view` tag for balanceOf function signature in IClaim interface ([here](https://github.com/Uniswap/v4-core/blob/1f350fa95e862ba8c56c8ff7e146d47c9043465e/src/interfaces/IClaims.sol#L13C5-L16C87)).
`function balanceOf(address account, Currency currency) external returns (uint256);`

### Expected Behavior

Should be a view function.

**Comment by saucepoint** [comment]
thanks for flagging this, its legacy deadcode now. The custom interface was recently replaced with ERC-6909

If you're looking to test out claims functionality, please refer to [IERC6909Claims ](https://github.com/uniswap/v4-core/blob/main/src/interfaces/external/IERC6909Claims.sol)
