### ISSUE TITLE
[Bug]: How to find the Quoter Contract of Sepolia Testnet?

### ISSUE THREAD

**Issue by liubin595338764** [Uniswap/v4-core#458]
### Describe the bug

Hello, I am using the V3 SDK to getting a quote. It uses the `0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6` Quoter Contract on the Ethereum Mainnet for querying quotes.

However, I cannot find which Quoter Contract should be used on the Sepolia testnet?

Please kindly let me know.

```js
// constants.ts
export const QUOTER_CONTRACT_ADDRESS =  '0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6'

// [quote.ts](https://github.com/Uniswap/examples/blob/main/v3-sdk/quoting/src/libs/quote.ts)
const quoterContract = new ethers.Contract(
  QUOTER_CONTRACT_ADDRESS,
  Quoter.abi,
  getProvider()
)
```

### Expected Behavior

Please tell me the Quoter Contract of Sepolia Testnet.

**Comment by saucepoint** [comment]
going to close this since its related to v3. Looks like Quoter (or QuoterV2) hasnt been deployed on sepolia. feel free to deploy yourself
