### ISSUE TITLE
Custom ERC1155 contract

### ISSUE THREAD

**Issue by hensha256** [Uniswap/v4-core#46]
This will enable us to have optimisations and simplifications over the generic OZ one.

Personalisation of the transfer function:
If the `to` address is the PoolManager, and the PoolManager is locked, automatically burn the tokens and update the account delta - no need to call the receiving hook

**Comment by zerosnacks** [comment]
A tip if you are looking to start with a highly optimized ERC1155 base contract: https://github.com/Vectorized/solady/blob/main/src/tokens/ERC1155.sol

**Comment by netnose** [comment]
@MicahZoltu i think that a data URI can be a good fit. It respects EIP-1155 and preserves users privacy.
Solidity can build data URIs dynamically and the impact on gas fees is just on deployment phase.

Uniswap v3 uses this strategy: https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/NFTDescriptor.sol

**Comment by MicahZoltu** [comment]
A data-URI generated on chain is a neat workaround, and I would accept that as being immutable, trustless, and censorship resistant.  It seems quite gas wasteful compared to just storing the data in a native format, but if one insists on using EIP-1155 this is a good workaround!

**Comment by netnose** [comment]
Why do you think it is gas wasteful?
The functions returning the data URIs will be used in reading operations, are gas-free.
Data used to build the URIs is already stored on-chain and no additional storage is required to build them.

Am I missing something?

**Comment by MicahZoltu** [comment]
Good point about callers being off-chain.  And I suppose you can pre-construct most of the data-URI and only fill in the specific unit details when you construct it.  Consider me convinced on the data URI solution!

**Comment by zhongeric** [comment]
Closed by #379
