### ISSUE TITLE
Have {beforeSwap, afterSwap} return adjustments to {amountSpecified, swapper's delta in unspecified token}, respectively

### ISSUE THREAD

**Issue by danrobinson** [Uniswap/v4-core#463]
### Component

Hooks, Lock and Call, Delta accounting

### Describe the suggested feature and problem it solves.

This is a proposal for how v4 could implement custom accounting and flexible hook fees for pools. This change builds on #442. I think this solution could either be a substitute for #450 or a complement to it.

I suggest we have the beforeSwap() and afterSwap() hooks each return a single value which can be applied as a delta to amountSpecified and the user's delta in the unspecified token, respectively. The changes would be balanced by changes to the hook's own transient balance in the respective token. This would add support for new kinds of hooks, while simplifying the router logic around hook fees, no-op pools, and other features.

Credit to @alexnezlobin for many of the ideas below. 

## Problem

I generally like the approach to locking and transient balances in #442 and #450, but there are some limitations and oddities in it:

* There is no way for a beforeSwap hook to adjust the amount that is swapped on the pool (other than with NO_OP, which cancels it altogether).
* The deltas returned by the swap() function don't match the deltas that will ultimately be applied to the user's balances as a result of the swap.
* There are limited guarantees about what a swap will ultimately do to the user's transient balances.
* Hook fees and custom-accounting pools (no-ops) require special support and handling from the router, which requires some extra calls to the singleton.

##  Interface and functionality

* Here are my thoughts on the ideal behavior that a "custom accounting" system would support if possible:
  * swap() should have a predictable interface and rules for its behavior. This allows the router to interact with pools and not have to deal with (or perform expensive checks for) surprising edge cases. My proposal is that those rules should match the general rules for v1+v2+v3 pools. Namely:
    * swap() should have the same behavior for all pools, including vanilla pools, pools that take some of the input or output tokens as hook fees, or no-op pools that work some other way. The router shouldn't have to treat no-op pools differently. (For example this line seems like a sign that something has gone wrong: https://github.com/Uniswap/v4-core/blob/one-dir-delta-resolver/src/PoolManager.sol#L219.) 
    * The swap() function should return the actual deltas that were applied to the user's transient balances during the swap (including updates that were applied by the hook as a no-op pool or through hook fees etc), not just the deltas that were applied by the concentrated liquidity swap logic itself.
    * The deltas applied for one of the tokens should respect the amountSpecified argument. If the router calls swap to sell 100 USDC, it should be guaranteed that the user's transient balance of USDC has gone down by 100 after the swap. If the router calls swap to buy 100 USDC, it should be guaranteed that the user's transient balance of USDC has gone up by 100 after the swap.
    * Deltas applied should respect the zeroForOne argument. A zeroForOne swap should never cause the token1 balance to go down, and a !zeroForOne swap should never cause the token0 balance to go down.
    * In a swap() on a pool between two tokens, the hook should not be able to take a third token from the user (at least without some special support and handling in the router, which should be considered exceptional).
  * Within those rules, I think hooks should be maximally flexible (if they have the custom accounting permission enabled).
    * Hooks should be able to reduce the user's delta in either token for their own benefit, or to increase the user's delta in either token at their own cost, as long as the rules above are are obeyed. This should be supported in the swap function itself (rather than requiring extra action from the router).
    * Hooks should be able to change the amount that actually gets traded on the v3 pool.
Note that this would mean changing the value of amountSpecified passed into Pool.swap() (which I'll call amountSwapped), but that (as discussed above) the user would still be guaranteed that the resulting deltas from the whole swap would obey the amountSpecified. (So any adjustment to amountSwapped changes the amount swapped on the pool and the hook's balance in that token by offsetting amounts, without changing the swapper's delta.)
      * I think no-op hooks should be implemented as hooks that set the amountSwapped to 0, rather than special cases.
    * Hooks should be able to maintain and settle their own transient balances. Generally the hook should be expected to keep track of and take care of those balances, rather than the router having to check for them.
      * The main use case I can think of is a hook that wants to take tokens from the swapper and redistribute them immediately within the singleton (i.e. by depositing them as liquidity, donating them to LPs, by swapping them on the same pool or another pool, etc).

### Describe the desired implementation.

This assumes that #442 is merged.

* Have beforeSwap() return an int for hookTakenInSpecified. This is subtracted from amountSpecified (turning it into amountSwapped, which is then passed to swap) and is subtracted from the hook’s own transient balance in the specified token.
* Have afterSwap() return an int for hookTakenInUnspecified. This is added to the swapper's delta in the unspecified token and subtracted from the hook's transient balance in the unspecified token.
* Add checks at the end of the swap function that the sign of the user's delta for the unspecified token obeys the zeroForOne rule.
* Add a permission flag for ADJUST_AMOUNTS_FLAG (or something) without which the return values for hookTakenInSpecified and hookTakenInUnspecified are ignored.
* Eliminate the NO_OP_FLAG and logic around no-ops; those can now be implemented by having the hook return a hookTakenInSpecified that is equal to amountSpecified (thus reducing amountSwapped to zero).

### Describe alternatives.

One open question is how this should interact with the payOnBehalf function added in #450. My suggestion would probably be to merge it without #450, but am open to arguments on the other side.

* Merge this without #450. I think this supports most use cases for custom accounting, but wouldn't support some special cases where (say) the hook might want to take transient balances in a third token from a user.
  * I think most use cases where a hook would want to pay balances in a third token to a user could just be done with ERC-6909 or ERC-20 balances.
* Merge both this and #450. This provides two ways for the hook to make extra payments in transient balances to the user, and allows the hook to take payments in a third token from the user. There are different ways this could be accomplished:
  * Leave it as is. This would mean that sometimes swaps would result in updates to transient balances that weren't expected and that the router would have to handle.
  * Measure any changes to user's deltas that occurred during the hooks and add those into the amountDeltas returned by swap(). This would mean that any extra input or output tokens that the hook sent to the user would be accounted for in what is told to the router. However, it wouldn't tell the router about any transient balances in any other tokens that were sent.
    * Two suboptions: do this and enforce the amountSpecified rule on the final delta, or do this and don't enforce that rule.
* Just merge #450. As discussed above, this doesn't support all desired use cases and requires extra handling from the router.

**Comment by hensha256** [comment]
A note here - PR #482 adds this but does not add the extra return of `hookDeltaInUnspecified` to `beforeSwap` as well as `afterSwap`.

I want to consider if that return is beneficial in a second PR
