### ISSUE TITLE
Skip reservesOf for native

### ISSUE THREAD

**Issue by marktoda** [Uniswap/v4-core#464]
### Component

Delta accounting

### Describe the suggested feature and problem it solves.

We can make native accounting cheaper by using msg.value instead of reservesOf diff to track incoming native assets.

Main downside I can think of is that now native _must_ be sent via the `settle` call with payable. So we also should remove the receive fallback and lose any use cases that involve raw sending ETH into the poolManager. These are likely rare use cases and the gas savings are worth it IMO

### Describe the desired implementation.

Settle: if native, paid = msg.value else reserves diff

```
    /// @inheritdoc IPoolManager
    function settle(Currency currency) external payable override noDelegateCall onlyByLocker returns (uint256 paid) {
        if (currency.isNative()) {
           paid = msg.value;
        } else {
           uint256 reservesBefore = reservesOf[currency];
           reservesOf[currency] = currency.balanceOfSelf();
           paid = reservesOf[currency] - reservesBefore;
        }
        // subtraction must be safe
        _accountDelta(currency, -(paid.toInt128()));
    }
```

Take: if native, no need to update reserves

```
    /// @inheritdoc IPoolManager
    function take(Currency currency, address to, uint256 amount) external override noDelegateCall onlyByLocker {
        if (!currency.isNative) reservesOf[currency] -= amount;
        _accountDelta(currency, amount.toInt128());
        currency.transfer(to, amount);
    }
```

**Comment by marktoda** [comment]
h/t @danrobinson

**Comment by danrobinson** [comment]
Could we keep the fallback but have it credit the accountDelta to msg.sender? Then they could use payOnBehalf to get it to someone else?

**Comment by snreynolds** [comment]
closed in this PR https://github.com/Uniswap/v4-core/pull/522
