### ISSUE TITLE
Make reservesOf transient and add `sync` function

### ISSUE THREAD

**Issue by danrobinson** [Uniswap/v4-core#466]
### Component

Gas Optimization, Singleton

### Describe the suggested feature and problem it solves.

This is a meaningful gas optimization (5k+ gas for any swap where an ERC-20 leaves the singleton). It would save an SSTORE per call for each `take`, and save an SSTORE call for each `settle` at the cost of two extra CALLs (which should still be a net savings). It is complementary to #464, which would implement slightly greater gas savings for native ETH; this change provides an optimization for ERC-20 tokens.

### Describe the desired implementation.

Right now, the singleton tracks its reserves in every ERC-20 token in the `reservesOf` mapping, which adds an SSTORE to every `take` and every `settle` call. This mapping is only used in those two functions, and its only purpose is to allow `settle` to measure the amount of tokens that have been recently transferred into the contract. This could be more efficiently implemented by making `reservesOf` transient, removing the update from `take`, and adding a `sync(Currency currency, address account)` function that updates `reservesOf` to the current balance of the token.

When a router wants to `settle` a token, it would have to call `sync` for the user on that token before transferring any tokens to the singleton.

### Describe alternatives.

Instead of using transient storage, the singleton could do a balance check and then call back into the router (which would be responsible for transferring the tokens); this would require more complexity in the router and is likely less safe.

### Additional context.

One downside of this change is that tokens that are sent to the contract (or balances that accrue as interest) without a preceding `sync` call become inaccessible, rather than being given away to whoever is the next caller of `settle`. Since right now these tokens are effectively given away to MEV, I don't think this matters for real users of the contract.

**Comment by hensha256** [comment]
What is the need for `sync` to have 2 parameters? Can it not just be `sync(currency)`?

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$13.63 USD** for a successful merge request of this issue via contributions such as **1.21875 UNI** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)
