### ISSUE TITLE
wen npmjs ?

### ISSUE THREAD

**Issue by daviidarr** [Uniswap/v4-core#470]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

Hi,

npm --save-dev install @uniswap/v4-core
would be better than what is described on https://soliditydeveloper.com/uniswap4

Looking fwd to build on you.

**Comment by kyscott18** [comment]
Simply adding a `package.json` file would allow this repository to be imported with using GitHub dependencies

**Comment by hensha256** [comment]
hey! we likely wont be publishing on npm until the code is finalised and audited. I would recommend for now using git submodules!
