### ISSUE TITLE
Q&A: Governance for Hooks

### ISSUE THREAD

**Issue by alfellati** [Uniswap/v4-core#486]
Is there a mechanism to govern hooks, I mean certain pools could be deployed with malicious hooks to steal user funds right? How do we make sure those pools or hooks are not called or routed to?

I heard @haydenadams say that a Hook could be built to sort of take out-of-tick liquidity out of the position and use it in a lending protocol to earn yield. So I think there should be a way to protect Uniswap users from malicious hooks that could steal LPs liquidity. How do you guys approach this issue, is it governance that approves the pools with hooks or is there something in the Router to make a `SwapPathList` or an `ApprovedSwapPathList` for pools with hooks etc.?

I'd appreciate your answer.

**Comment by hensha256** [comment]
hey! this is definitely a largely unsolved problem for now - but the Uniswap Foundation have given out some grants to talented teams to help solve this problem! For example see this grant [here](https://twitter.com/UniswapFND/status/1773421514685059343).
