### ISSUE TITLE
Handle `settle()` for `Currency` type

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-core#494]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

_Suggestion_:
* support `currency.settle(...)` in the `CurrencyLibrary`

_Problem_:
Periphery contracts (swap router, position manager) have to handle token settlement for ERC20s, Native, and ERC6909s

these contracts commonly share a settle handler, i.e.:
```solidity
    function settle(Currency currency, IPoolManager manager, address payer, uint256 amount) internal {
        if (isNative(currency)) {
            manager.settle{value: amount}(currency);
        } else {
            IERC20Minimal(Currency.unwrap(currency)).transferFrom(payer, address(manager), amount);
            manager.settle(currency);
        }
    }
```

### Describe the desired implementation.

Add `settle()` to `CurrencyLibrary.sol`:

```solidity
    function settle(Currency currency, IPoolManager manager, address payer, uint256 amount, bool burn) internal {
        if (isNative(currency)) {
            manager.settle{value: amount}(currency);
        } else if (burn) {
            manager.burn(payer, toId(currency), amount);
        } else {
            IERC20Minimal(Currency.unwrap(currency)).transferFrom(payer, address(manager), amount);
            manager.settle(currency);
        }
    }
```

this would allow periphery contracts to directly settle any currency, without need of a custom a check

```solidity
data.key.currency0.settle(poolManager, data.sender, uint256(uint128(delta.amount0())), burn);
```

### Additional context.

Probably incurs a slight gas overhead?

For consistency, we may want to add `Currency.take(IPoolManager, address receiver, uint256 amount, bool mint)` too

**Comment by saucepoint** [comment]
from snapshots, we're saving maybe 6 gas on PoolSwapTest

with `Currency.take` it saves maybe 30 gas!

---

Sort of comes down to whether or not we want make CurrencyLibrary more opinionated/coupled with PoolManager operations..

**Comment by snreynolds** [comment]
Interesting! I do think its very sleek. I wonder if something like this could rather be implemented in a library in periphery? Just feels odd to expose two different `settle` / `take` entrypoints inside core. But I'm definitely not opposed if you feel strongly

**Comment by saucepoint** [comment]
i think periphery could make sense -- especially to support permit2 signature settles? 

the one benefit of putting it in core's CurrencyLibrary is 1 import and 1 `using` statement and you're good to go, but is kind of minor

**Comment by hensha256** [comment]
We've agreed for now this should live in periphery
