### ISSUE TITLE
Support testing/experimentation with other environment than foundry

### ISSUE THREAD

**Issue by Amxx** [Uniswap/v4-core#512]
### Describe the suggested feature and problem it solves.

[PoolTestBase.sol](https://github.com/Uniswap/v4-core/tree/main/src/test/PoolTestBase.sol) is used for testing both here and in v4-periphery, where [HookEnabledSwapRouter.sol](https://github.com/Uniswap/v4-periphery/blob/main/test/utils/HookEnabledSwapRouter.sol) depends on it. `PoolTestBase.sol` depends on `forge-std/Test.sol`, which is foundry specific. (for `assertGt` and `assertLt`).

These contract are usefull to testing potential integration with UniswapV4, both using foundry and other environment. In particular, my testing involves nes EIP candidate that I have implemented in hardhat-core and in ethers.js. 

I lost the hability to test since I pulled a new version of v4-core and v4-periphery, because this dependency on the Foundry Vm.

### Describe the desired implementation.

Would it be possible to avoid depending on the Foundry Vm for that (and use a normal `require` or a custom error) ? You're making it unecessarily difficult to test using other environments.

### Describe alternatives.

Provide a set of "preset" contracts that implement a minimum viable example of v4 (manager + provide liquidity + do a swap) that have no foundry dependency

### Additional context.

[This is the tests I'm working on](https://github.com/Amxx/EIP-5806/tree/main/packages/test-uniswap) (impact of EIP-5806 tx on usage and gas cost).

**Comment by saucepoint** [comment]
thanks for flagging this. im in favor of the change! we should be able to replace all the asserts with require statements

especially because the contracts are in 'src/' and not 'test/'

**Comment by hensha256** [comment]
Fixed in #516
