### ISSUE TITLE
Update Dune data to include v4

### ISSUE THREAD

**Issue by codyborn** [Uniswap/v4-core#521]
Once we deploy v4, we want Dune to pick up v4 data. This includes events, call traces, and views built off this raw data.

To get events and call traces, provide the Dune team with ABI and deployment addresses.
These can be added here: https://dune.com/contracts/new

We need to ensure all downstream views are also updated. For example `dex.trade` is a heavily used table (see [Austin's queries](https://dune.com/austin_adams)). 

These intermediate views are tracked in this repo: https://github.com/duneanalytics/spellbook/

We can create a PR to update the views with the new data.

**Comment by snreynolds** [comment]
Going to track this on linear, thank you @codyborn !
