### ISSUE TITLE
Use CurrencyDelta for Currency

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-core#538]
### Describe the suggested feature and problem it solves.

I think it would be a readability improvement if we used the CurrencyDelta library with the other syntax, especially now that we are passing in a target address.

ie instead of `CurrencyDelta.get(target, currency);` we could do `currency.getDeltaFor(target)`;

**Comment by nishim3** [comment]
I want to try my hand at this. Can you assign it to me please?
