### ISSUE TITLE
[Bug]: CurrencyNotSettled during multi-path swap 

### ISSUE THREAD

**Issue by zhoumutou** [Uniswap/v4-core#540]
### Describe the bug

There ara two pairs **OP <=> USDC** and **ETH <=> OP**.
When swaping 10 USDC for ETH:
1. OP => USDC
- amountIn: 10000000000000000000(OP)
- amountOut: 20003955641254000543(USDC)

2. USDC => ETH
- **amountIn: 20003955641254000543(USDC) (Expected)**
- **amountIn: 20003955641254000544(USDC) (Required)**
- amountOut: 2000191612819580(ETH)

Report `revert CurrencyNotSettled()` error.

### Expected Behavior

1. OP => USDC
- amountIn: 10000000000000000000(OP)
- amountOut: 20003955641254000544(USDC)

### Additional context

├─ [163865] Swap::swap{value: 10000000000000}([SwapPath({ key: PoolKey({ currency0: OP, currency1: USDC, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), params: SwapParams({ zeroForOne: false, amountSpecified: 20003955641254000543 [2e19], sqrtPriceLimitX96: 56022828606855765386542969247 [5.602e28] }) }), SwapPath({ key: PoolKey({ currency0: ETH, currency1: OP, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), params: SwapParams({ zeroForOne: false, amountSpecified: 2000191612819580 [2e15], sqrtPriceLimitX96: 8002868273889118125230824649892 [8.002e30] }) })], DD43, 10000000000000 [1e13])
│   ├─ [155297] PoolManager::unlock()
│   │   ├─ [153230] Swap::unlockCallback()
│   │   │   ├─ [34122] PoolManager::swap(PoolKey({ currency0: OP, currency1: USDC, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), SwapParams({ zeroForOne: false, amountSpecified: 20003955641254000543 [2e19], sqrtPriceLimitX96: 56022828606855765386542969247 [5.602e28] }), 0x)
│   │   │   │   ├─ [4184] FullRange::beforeSwap(Swap, PoolKey({ currency0: OP, currency1: USDC, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), SwapParams({ zeroForOne: false, amountSpecified: 20003955641254000543 [2e19], sqrtPriceLimitX96: 56022828606855765386542969247 [5.602e28] }), 0x)
│   │   │   │   │   └─ ← 0x575e24b400000000000000000000000000000000000000000000000000000000
│   │   │   │   ├─ emit Swap(id: OP-USDC, sender: Swap, amount0: 20003955641254000543 [2e19], amount1: -10000000000000000000 [-1e19], sqrtPriceX96: 56022828606855765386542969247 [5.602e28], liquidity: 70781388796773407195166 [7.078e22], tick: -6932, fee: 0)
│   │   │   │   └─ ← 6806993373387370683523570849941101510513187591887731032064 [6.806e57]
│   │   │   ├─ [15314] USDC::transferFrom(DD43, PoolManager, 10000000000000000000 [1e19])
│   │   │   │   ├─ emit Transfer(from: DD43, to: PoolManager, value: 10000000000000000000 [1e19])
│   │   │   │   └─ ← true
│   │   │   ├─ [7999] PoolManager::settle(USDC)
│   │   │   │   ├─ [582] USDC::balanceOf(PoolManager) [staticcall]
│   │   │   │   │   └─ ← 60155050988275450000022 [6.015e22]
│   │   │   │   └─ ← 10000000000000000000 [1e19]
│   │   │   ├─ [38414] PoolManager::swap(PoolKey({ currency0: ETH, currency1: OP, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), SwapParams({ zeroForOne: false, amountSpecified: 2000191612819580 [2e15], sqrtPriceLimitX96: 8002868273889118125230824649892 [8.002e30] }), 0x)
│   │   │   │   ├─ [4184] FullRange::beforeSwap(Swap, PoolKey({ currency0: ETH, currency1: OP, fee: 8388608 [8.388e6], tickSpacing: 60, hooks: FullRange }), SwapParams({ zeroForOne: false, amountSpecified: 2000191612819580 [2e15], sqrtPriceLimitX96: 8002868273889118125230824649892 [8.002e30] }), 0x)
│   │   │   │   │   └─ ← 0x575e24b400000000000000000000000000000000000000000000000000000000
│   │   │   │   ├─ emit Swap(id: ETH-USDC, sender: Swap, amount0: 2000191612819580 [2e15], amount1: -20003955641254000544 [-2e19], sqrtPriceX96: 8002868273889118125230824649892 [8.002e30], liquidity: 9999000000000001000 [9.999e18], tick: 92309 [9.23e4], fee: 0)
│   │   │   │   └─ ← 680629936305656344351040025822591643012113888331319392 [6.806e53]
│   │   │   ├─ [14024] PoolManager::take(ETH, DD43, 2000191612819580 [2e15])
│   │   │   │   ├─ [0] DD43::fallback{value: 2000191612819580}()
│   │   │   │   │   └─ ← ()
│   │   │   │   └─ ← ()
│   │   │   ├─ [22641] FeeController::collectFee{value: 10000000000000}(ETH-USDC)
│   │   │   │   └─ ← ()
│   │   │   └─ ← 0x
│   │   └─ ← CurrencyNotSettled()
│   └─ ← CurrencyNotSettled()
└─ ← CurrencyNotSettled()

**Comment by saucepoint** [comment]
without seeing your Swap Router code, `CurrencyNotSettled` indicates that there is an outstanding credit (pool manager owes you) or a debt (you owe the pool manager). would make sure the Swap Router is calling settle / take correctly

**Comment by zhoumutou** [comment]
Swap Router Code
`
struct SwapPath {
    PoolKey key;
    IPoolManager.SwapParams params;
}

struct CallbackData {
    address sender;
    address to;
    uint256 swapFee;
    SwapPath[] paths;
 }

function swap(SwapPath[] calldata paths, address to, uint256 swapFee) external payable override {
    poolManager.unlock(abi.encode(CallbackData(msg.sender, to, swapFee, paths)));
}

function unlockCallback(bytes calldata rawData) external override poolManagerOnly returns (bytes memory) {
    CallbackData memory data = abi.decode(rawData, (CallbackData));

    uint256 length = data.paths.length;
    SwapPath memory path = data.paths[0];
    BalanceDelta delta = poolManager.swap(path.key, path.params, ZERO_BYTES);
    _accountSettleDelta(data.sender, path.key, delta);

    for (uint256 i = 1; i < length; ) {
        path = data.paths[i];
        delta = poolManager.swap(path.key, path.params, ZERO_BYTES);
        unchecked {
            ++i;
        }
    }
    _accountTakeDelta(data.to, path.key, delta);

    return ZERO_BYTES;
}

function _accountSettleDelta(address sender, PoolKey memory key, BalanceDelta delta) internal {
    if (delta.amount0() < 0) {
        _settleDelta(sender, key.currency0, uint128(-delta.amount0()));
    } else {
        _settleDelta(sender, key.currency1, uint128(-delta.amount1()));
    }
}

function _accountTakeDelta(address to, PoolKey memory key, BalanceDelta delta) internal {
    if (delta.amount0() > 0) {
        _takeDelta(to, key.currency0, uint128(delta.amount0()));
    } else {
        _takeDelta(to, key.currency1, uint128(delta.amount1()));
    }
}

function _settleDelta(address sender, Currency currency, uint128 amount) internal {
    if (currency.isNative()) {
        poolManager.settle{value: amount}(currency);
    } else {
        IERC20Minimal(Currency.unwrap(currency)).transferFrom(sender, address(poolManager), amount);
        poolManager.settle(currency);
    }
}

function _takeDelta(address to, Currency currency, uint128 amount) internal {
    poolManager.take(currency, to, amount);
}
`

PS: The probability of such a situation occurring is relatively low.

**Comment by saucepoint** [comment]
I think you can simplify this a bit by the using the outputs (delta) of the first swap as the params of the second swap? a bit odd how you're specifying the swap amounts on the second swap

after performing all the swaps, i would then call `manager.currencyDelta(...)` to get deltas for the input / output tokens

as a reminder too -- a negative `SwapParams.amountSpecified` indicates an exact input swap

**Comment by zhoumutou** [comment]
Thank you for your advice

> I think you can simplify this a bit by the using the outputs (delta) of the first swap as the params of the second swap? a bit odd how you're specifying the swap amounts on the second swap
> 
> after performing all the swaps, i would then call `manager.currencyDelta(...)` to get deltas for the input / output tokens
> 
> as a reminder too -- a negative `SwapParams.amountSpecified` indicates an exact input swap
