### ISSUE TITLE
Move hook bit flags to LSBs

### ISSUE THREAD

**Issue by Philogy** [Uniswap/v4-core#553]
### Component

Hooks

### Describe the suggested feature and problem it solves.

Instead of using the most significant bits of the hook address to configure the different hook flags I suggest using the lower, least significant bits. This will allow people to mine and use classical vanity addresses with leading zero bytes for their hooks without worrying about the impact that might have on the hook's permissions.

**Comment by nishim3** [comment]
It will cause problems in using ```vm.etch```. It does not deal well with address values in a range of [1-10](https://github.com/foundry-rs/foundry/issues/1159).

**Comment by Philogy** [comment]
> It will cause problems in using ```vm.etch```. It does not deal well with address values in a range of [1-10](https://github.com/foundry-rs/foundry/issues/1159).
> 
> 

What does that have to do with my proposal? I was only suggesting the lower bits are interpreted as the hook flags to allow for addresses with some leading zeros not addresses in the range 1-10.

**Comment by nishim3** [comment]
Sorry for the misunderstanding! I have opened a PR with what I think is the desired implementation. Do have a look.
