### ISSUE TITLE
Return swapFee in beforeSwap for hooks with relevant permission

### ISSUE THREAD

**Issue by danrobinson** [Uniswap/v4-core#554]
### Component

Hooks, Gas Optimization

### Describe the suggested feature and problem it solves.

Requiring `beforeSwap` hooks to call `updateDynamicSwapFee` to change the fee adds around 3000 gas overhead.

Allowing hooks that have the appropriate permission to return a `swapFee` value from `beforeSwap` would save this gas.

### Describe the desired implementation.

After landing #482 (which adds an int128 return value to `beforeSwap`), add a uint24 return value for newDynamicSwapFee, that is used if the hook has dynamic fee permissions.

Some value (maybe max(uint24)?) could be defined as a sentinel value that would not update the swap fee even for dynamic fee hooks.

```
    function beforeSwap(
        address sender,
        PoolKey calldata key,
        IPoolManager.SwapParams calldata params,
        bytes calldata hookData
    ) external returns (bytes4, int128, int128, );
```

See example possible implementation: https://github.com/saucepoint/v4-core/pull/3/files#diff-ff33f731a6fff1d6a1c4bdde67f734199c88a742966c3942a4fac5ab9be7c07fR248

### Describe alternatives.

We could leave the contract as it is.

We could make this the only way to do dynamic fees (rather than having any caching).

**Comment by saucepoint** [comment]
(temporarily flagging this as blocked until we merge return deltas, which does a lot of heavy lifting for returning & reading values from beforeSwap)
