### ISSUE TITLE
[Bug]: settle may leave unrecoverable msg.value in contract

### ISSUE THREAD

**Issue by wei3erHase** [Uniswap/v4-core#555]
### Describe the bug

Since #522, when calling `settle` with `Currency != NATIVE` AND `msg.value`, the method will account the currency erc20 balance, ignore the `msg.value`, and the ETH will be locked forever in the contract (as it'll not be settable by anyone).

### Expected Behavior

Method should revert when currency is not native and msg has value.

**Comment by hensha256** [comment]
Nice, thanks for submitting this! Looks like a community member is already fixing it in a PR 🙏
