### ISSUE TITLE
[Bug]: Ownership can be irreversibly lost

### ISSUE THREAD

**Issue by jeffishjeff** [Uniswap/v4-core#618]
### Describe the bug

The `Owned.sol` implementation in solmate is vulnerable to maliciously/erroneously transfer of ownership to an uncontrolled address, akin to "unsafe transfer" in token standards, resulting in the ownership on `PoolManager` to be lost forever.

### Expected Behavior

Implement a custom contract with double confirmation instead. It stores two variables, a `successor` in addition to the `owner`, and provides two methods:

- `appoint(address)` which is `onlyOwner` and sets `successor`
- `succeed()` which reverts unless `msg.sender == successor` then sets `owner = msg.sender` (and optionally clears `successor`)

**Comment by wjmelements** [comment]
I don't think this is a problem.
