### ISSUE TITLE
Import and modify BitMath implementation from Solady #257

### ISSUE THREAD

**Issue by marktoda** [Uniswap/v4-core#649]
### Describe the suggested feature and problem it solves.

BitMath is optimized heavily by importing and modifying mostSignificantBit and leastSignificantBit implementations from [Solady::LibBit](https://github.com/Vectorized/solady/blob/37b4fd04dd82977eb0161839389187abb7afdb58/src/utils/LibBit.sol) which uses the De Bruijn lookup.

**Comment by marktoda** [comment]
https://github.com/Uniswap/v4-core/pull/257

**Comment by snreynolds** [comment]
https://github.com/Uniswap/v4-core/pull/785/files and https://github.com/Uniswap/v4-core/pull/822
