### ISSUE TITLE
prevent negative and zero tickspacing

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/v4-core#68]
we need to prevent this somewhere, probably in initialize

this was prevented in createPool and enableFeeAmount before https://github.com/Uniswap/v3-core/blob/ed88be38ab2032d82bf10ac6f8d03aa631889d48/contracts/UniswapV3Factory.sol#L44
and
https://github.com/Uniswap/v3-core/blob/ed88be38ab2032d82bf10ac6f8d03aa631889d48/contracts/UniswapV3Factory.sol#L67

**Comment by wjmelements** [comment]
Why is tickSpacing a signed int24 instead of a uint24?
