### ISSUE TITLE
nit: not using removeOverrideAndValidate which is used in Pool.sol in PoolTest

### ISSUE THREAD

**Issue by zhongeric** [Uniswap/v4-core#684]
```
        // TODO: consider why not using removeOverrideAndValidate which is used in Pool.sol
```

https://github.com/Uniswap/v4-core/blob/b538356117bbbf6617ee314d9b0cccb005950b6a/test/libraries/Pool.t.sol#L123

**Comment by hensha256** [comment]
We dont use that method in the test because it would cause an uncaught revert in the test - we want to execute `swap` with the invalid lp fee, and check that swap still reverts when that happens. That is caught in an if statement later in the test
`} else if (!swapFee.isValid()) {`
