### ISSUE TITLE
Places that could use extra explanatory comments IMO 

### ISSUE THREAD

**Issue by marktoda** [Uniswap/v4-core#709]
### Component

Singleton

### Describe the suggested feature and problem it solves.

- Why events are emitted so high up in the operation functions (i.e. because they need to be before afterXYZ to keep ordering)
- general CA explainer in swap + modifyPosition when we update callerDelta and hookDelta
- in swap we say "// if the hook doesnt have the flag to be able to return deltas, hookDelta will always be 0." above the hook call, but think this should be a few lines below when we check the return value
- why do we need the _swap internal function when its only called once?
- " // subtraction must be safe" comments could use more explanation - not sure what they mean here

**Comment by snreynolds** [comment]
Closing - most of this fixed in https://github.com/Uniswap/v4-core/pull/715
