### ISSUE TITLE
[Bug]: immutable controllerGasLimit enforced with GAS opcode

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/v4-core#739]
### Describe the bug

It is unclear why the controllerGasLimit design was chosen.

As far as I can tell, the immutable controllerGasLimit is a bad mechanism. The gas costs of opcodes are not fixed and can change with a protocol upgrade. Hard forks can and have increased gas costs. This `gasleft` mechanism is not future-proof and is worse than a simpler design.

### Expected Behavior

Revert if protocolFeesForPool fails.

**Comment by hensha256** [comment]
This was introduced to fix #221. We would rather a call to the protocol fee controller ran out of gas, and the protocol fee initialzied to 0, than pools be unable to initialize.

> is worse than a simpler design.

What simpler design did you have in mind? We are open to changing it for a design that fixes both issues!

**Comment by wjmelements** [comment]
> Revert if protocolFeesForPool fails.

**Comment by wjmelements** [comment]
> Bad Owner Can Brick initialize By Setting A Bad protocolFeeController

Why not accept this behavior?

**Comment by wjmelements** [comment]
> Alternatively, it should be made more explicit that the owner can globally shut down the creation of new pools via the initialize function.

This should have been the solution.

**Comment by wjmelements** [comment]
In fact the original problem still persists because
```
            _checkProtocolFee(protocolSwapFee);
            _checkProtocolFee(protocolWithdrawFee);
```
happens outside of the `catch`. So they can still return invalid protocol fees to block `initialize`.

**Comment by hensha256** [comment]
I think youre looking at an old branch maybe? Theres no `try / catch` in the contract, and theres no `protocolWithdrawFee` nor `_checkProtocolFee`.

Do you mind looking at `main` and seeing if you still find an issue?

**Comment by wjmelements** [comment]
You are right. I was looking at 6b8ec7c6dff9a2bef4ff408f886b4cc1737179ae. The current version is better than what I was looking at.

I suppose I am okay with the protocol fees going to zero in the event of gas cost increases.
