### ISSUE TITLE
Document the Finalized Initcode

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/v4-core#918]
### Describe the suggested feature and problem it solves.

The initcode hash is published but the initcode is not. If the initcode matching the initcode hash were to be lost, it could cause issues with the final deployment next year.

### Describe the desired implementation.

Commit the finalized output files into version control. These include the initcode and the ABI.

### Describe alternatives.

Commit separate files with the final initcode and ABI.

### Additional context.

I am having trouble generating initcode that matches the published initcode hash.

I worry that the initcode hash in the [contest contract](https://etherscan.io/address/0x48e516b34a1274f49457b9c6182097796d0498cb#code) may be incorrect because I cannot reproduce it. I calculate `0x44d2e366954aa5a7f0605ffd66ca57a5a71987845939d8d8c79c716d8dfbb3de` instead. Here is how:

I checkout `main` and do `forge update` and `forge build`.

I do `cat out/PoolManager.t.sol/PoolManagerTest.json | jq -r .bytecode.object > v4.out`

In python3 I do:
```
from web3 import Web3
with open('v4.out', 'r') as f:
    v4 = f.read().rstrip()
print(Web3.keccak(hexstr=v4))
```
The result is `0x44d2e366954aa5a7f0605ffd66ca57a5a71987845939d8d8c79c716d8dfbb3de`.

**Comment by gretzke** [comment]
constructor arguments are part of the initcode so they need to be taken into account. The hash that you found (`0x2aa0ab6866fc2e2b2a0a9128e66982a049eb04516c012690426ab110f92966f8`) is the initcode encoded with the zero address as a constructor argument. If you take the Governance timelock address and encode it with the bytecode you will find that the initcode hash matches the one from the competition
